### ISSUE TITLE
Thanks for sharing!

### ISSUE THREAD

**Issue by sberryman** [starasteh/tisvge2e#1]
I found it extremely similar to the work by @corentinj and his [Real time voice cloning project.](https://github.com/CorentinJ/Real-Time-Voice-Cloning)

I spent a lot of time reproducing and re-training the embedding model for speaker identification and diarization.

**Comment by starasteh** [comment]
@sberryman thank you for the comment.

I don't know about the work you mentioned, but in this repo, I'm basically using [Google's GE2E](https://arxiv.org/abs/1710.10467) method, which has not provided an official implementation, as my main method and comparing different scenarios with each other.

**Comment by sberryman** [comment]
Yeah, I realize it isn't a copy but it was neat to see how similar the implementations were. I also trained my embedding model on the entire [Common Voice](https://commonvoice.mozilla.org/) dataset (in addition to LibriTTS). 

You mention future work:
> For future work, we would like to further generalize the proposed method by replacing the initial feature extraction (cf. algorithm 1 and algorithm 3) by DL techniques in order to directly feed the raw waveform to the network.

I would be very interested in this as well. I had done some quick testing using `Conv1d`'s for the feature extractor. However, I don't recall how well this particular model performed.

```python
from torch import nn

nn.Sequential(
    nn.Conv1d(
        1,
        64,
        kernel_size=64,
        stride=8,
        padding=0,
        dilation=1,
    ),
    nn.ReLU(),
    nn.BatchNorm1d(64),

    # stack
    nn.Conv1d(64, 128, kernel_size=3),
    nn.ReLU(),
    nn.BatchNorm1d(128),
    nn.MaxPool1d(3, stride=3),

    nn.Conv1d(128, 256, kernel_size=3),
    nn.ReLU(),
    nn.BatchNorm1d(256),
    nn.MaxPool1d(3, stride=3),

    nn.Conv1d(256, 512, kernel_size=3),
    nn.ReLU(),
    nn.BatchNorm1d(512),
    nn.MaxPool1d(3, stride=3),

    # max pool
    nn.AdaptiveMaxPool1d(1),
    nn.Flatten(),
)
```

**Comment by starasteh** [comment]
Yeah sure. Thank you for sharing.
